id = "frosted-theme"
name = "Frosted Dark Theme"
version = "0.0.1"
schema_version = 1
authors = ["David Liu <davidas99017@gmail.com>"]
description = "A pleasant frosted glass dark theme"
repository = "https://github.com/daviiiL/frosted-theme.git"
